### ISSUE TITLE
License file should be different for different repository/project

### ISSUE THREAD

**Issue by vikassy** [amire80/commons_upload#4]
You can see here (https://github.com/amire80/commons_upload/blob/master/lib/commons_upload.rb#L21) that the license file is related to VisualEditor(also very specific to Language Screenshot). 

I can think of 2 ways to solve this: 
- Add the license file_name as argument to upload command of the gem. 
- Add the project_name(Eg: VisualEditor) as argument to upload command of the gem. [But with this, the license file is going to be specific to LanguageScreenshotBot].

**Comment by zeljkofilipin** [comment]
Sounds good to me. Do you want to work on it?

**Comment by vikassy** [comment]
Solved in commit: https://github.com/amire80/commons_upload/commit/0e84e3a2e3b9b13579167d1ddee9fb083fddca6f
